# Generated by Django 5.2.17 on 2026-09-15 17:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('genealogy', '0003_life_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('audio', models.FileField(upload_to='recordings/%Y/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'm4a', 'aac', 'wav', 'ogg', 'oga', 'opus', 'webm', 'flac'])])),
                ('language', models.CharField(blank=True, help_text='e.g. Gĩkũyũ, English, Kiswahili', max_length=60)),
                ('recorded_on', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('people', models.ManyToManyField(blank=True, related_name='recordings_about', to='genealogy.person', verbose_name='people talked about')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='genealogy.place')),
                ('speakers', models.ManyToManyField(blank=True, related_name='recordings_given', to='genealogy.person')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
