# Generated by Django 5.2.17 on 2026-09-17 07:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_recordings'),
        ('genealogy', '0003_life_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('document_type', models.CharField(choices=[('birth', 'Birth certificate'), ('marriage', 'Marriage certificate'), ('death', 'Death certificate'), ('school', 'School record'), ('land', 'Land or property document'), ('immigration', 'Immigration or travel record'), ('letter', 'Letter'), ('newspaper', 'Newspaper clipping'), ('church', 'Church record'), ('other', 'Other document')], default='other', max_length=20, verbose_name='type')),
                ('file', models.FileField(upload_to='documents/%Y/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp', 'tif', 'tiff', 'heic', 'txt', 'doc', 'docx'])])),
                ('date', models.DateField(blank=True, help_text='The date on the document itself, if it has one.', null=True)),
                ('date_approx', models.BooleanField(default=False, verbose_name='date is approximate')),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, help_text='Where it came from: a registry, an archive, or the relative who kept it.', max_length=200)),
                ('privacy', models.CharField(choices=[('family', 'Signed-in family only'), ('public', 'Anyone who visits')], default='family', help_text='Certificates usually hold private details, so they stay with signed-in family by default.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('people', models.ManyToManyField(blank=True, related_name='documents', to='genealogy.person')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='genealogy.place')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
