# Generated by Django 5.2.17 on 2026-09-15 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('maiden_name', models.CharField(blank=True, help_text='Family name before marriage, if different.', max_length=80)),
                ('nickname', models.CharField(blank=True, help_text='Helps tell apart people who share a name, e.g. “Sr.” or “Mama Wanjiru”.', max_length=80)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_date_approx', models.BooleanField(default=False, verbose_name='birth date is approximate')),
                ('birth_place', models.CharField(blank=True, max_length=120)),
                ('is_living', models.BooleanField(default=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('death_place', models.CharField(blank=True, max_length=120)),
                ('lineage', models.CharField(blank=True, help_text='Clan or lineage (mbarĩ / mũhĩrĩga).', max_length=80, verbose_name='clan / lineage')),
                ('biography', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='people/%Y/')),
                ('needs_review', models.BooleanField(default=False, help_text='Flag records whose details still need to be confirmed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['last_name', 'first_name', 'middle_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LifeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('birth', 'Birth'), ('baptism', 'Baptism / naming'), ('education', 'Education / graduation'), ('marriage', 'Marriage'), ('career', 'Career'), ('migration', 'Move / migration'), ('achievement', 'Achievement'), ('death', 'Death'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('date', models.DateField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='genealogy.person')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('date'), nulls_last=True), 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union_type', models.CharField(choices=[('marriage', 'Marriage'), ('customary', 'Customary / traditional marriage'), ('partnership', 'Partnership')], default='marriage', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('divorce', 'Divorce'), ('separation', 'Separation'), ('death', 'Death of a partner')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('partner_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unions_as_a', to='genealogy.person')),
                ('partner_b', models.ForeignKey(blank=True, help_text='Leave empty if the other partner is unknown.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unions_as_b', to='genealogy.person')),
            ],
            options={
                'ordering': ['start_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('biological', 'Biological'), ('adopted', 'Adopted'), ('step', 'Step'), ('foster', 'Foster')], default='biological', max_length=20)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='genealogy.person')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='genealogy.person')),
                ('union', models.ForeignKey(blank=True, help_text='The couple this child belongs to, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_links', to='genealogy.union')),
            ],
            options={
                'verbose_name': 'parent–child link',
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='genealogy_p_last_na_eef29a_idx'),
        ),
        migrations.AddConstraint(
            model_name='union',
            constraint=models.UniqueConstraint(fields=('partner_a', 'partner_b'), name='unique_union_pair'),
        ),
        migrations.AddConstraint(
            model_name='union',
            constraint=models.CheckConstraint(condition=models.Q(('partner_a', models.F('partner_b')), _negated=True), name='union_partners_differ'),
        ),
        migrations.AddConstraint(
            model_name='parentchild',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='unique_parent_child'),
        ),
        migrations.AddConstraint(
            model_name='parentchild',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('child')), _negated=True), name='parent_is_not_child'),
        ),
    ]
