# Generated by Django 5.2.17 on 2026-09-15 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0002_places_from_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('institution', models.CharField(max_length=160)),
                ('level', models.CharField(choices=[('primary', 'Primary school'), ('secondary', 'Secondary school'), ('vocational', 'Vocational / technical'), ('college', 'College'), ('university', 'University'), ('postgraduate', 'Postgraduate'), ('other', 'Other')], default='other', max_length=20)),
                ('field_of_study', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'education',
                'ordering': [models.OrderBy(models.F('start_year'), nulls_last=True), 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('employer', models.CharField(max_length=160)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('is_current', models.BooleanField(default=False, verbose_name='works here now')),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'work',
                'verbose_name_plural': 'work',
                'ordering': [models.OrderBy(models.F('start_year'), nulls_last=True), 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, verbose_name='lives here now')),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'home',
                'ordering': [models.OrderBy(models.F('start_year'), nulls_last=True), 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('category', models.CharField(choices=[('role', 'Role or title'), ('occupation', 'Occupation'), ('faith', 'Faith & church'), ('community', 'Community & groups'), ('heritage', 'Heritage & tradition'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name', 'pk']},
        ),
        migrations.AddField(
            model_name='person',
            name='birth_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Position among their parents' children (1 = firstborn). Leave empty to use birth dates.", null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='homeland',
            field=models.ForeignKey(blank=True, help_text="Where their family's roots or land are (mũciĩ).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeland_of', to='genealogy.place', verbose_name='ancestral home'),
        ),
        migrations.AddField(
            model_name='person',
            name='named_after',
            field=models.ForeignKey(blank=True, help_text='The relative this person was named after.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='namesakes', to='genealogy.person'),
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='kind',
            field=models.CharField(choices=[('country', 'Country'), ('region', 'Region / province'), ('county', 'County'), ('subcounty', 'Sub-county / district'), ('location', 'Location / ward'), ('town', 'Town / city'), ('village', 'Village'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The larger place this one is part of, e.g. the county a village is in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='genealogy.place'),
        ),
        migrations.AlterField(
            model_name='lifeevent',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='genealogy.place'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='births', to='genealogy.place', verbose_name='place of birth'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deaths', to='genealogy.place', verbose_name='place of death'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_place_name_in_parent'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='genealogy.person'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='education',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='genealogy.person'),
        ),
        migrations.AddField(
            model_name='education',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education', to='genealogy.place'),
        ),
        migrations.AddField(
            model_name='employment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='genealogy.person'),
        ),
        migrations.AddField(
            model_name='employment',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment', to='genealogy.place'),
        ),
        migrations.AddField(
            model_name='residence',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='genealogy.person'),
        ),
        migrations.AddField(
            model_name='residence',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residences', to='genealogy.place'),
        ),
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='people', to='genealogy.tag'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'person'), name='unique_bookmark'),
        ),
    ]
